- recipe/meta.yaml
> release boa 0.0.1.dev1

- recipe/meta.yaml
> release 0.0.1.dev2

- recipe/meta.yaml
> release boa 0.1.2

- .azure-pipelines/azure-pipelines-linux.yml
- .ci_support/linux_64_.yaml
- .scripts/build_steps.sh
- LICENSE.txt
- README.md
…nda-forge-pinning 2020.09.30.16.33.39
Checklist
> rerender, push 0.1.2 again

- recipe/meta.yaml
> release 0.1.3

- recipe/meta.yaml
> release boa 0.2.0

- .azure-pipelines/azure-pipelines-linux.yml
- .ci_support/linux_64_python3.6.____cpython.yaml
- .ci_support/linux_64_python3.7.____cpython.yaml
- .ci_support/linux_64_python3.8.____cpython.yaml
- recipe/meta.yaml
> release boa 0.3.0

- .ci_support/linux_64_python3.6.____cpython.yaml
- .ci_support/linux_64_python3.7.____cpython.yaml
- .ci_support/linux_64_python3.8.____cpython.yaml
- .scripts/run_docker_build.sh
- recipe/meta.yaml
> release boa 0.3.1

- recipe/meta.yaml
> release 0.3.2

- .ci_support/linux_64_python3.9.____cpython.yaml
- .ci_support/osx_arm64_python3.8.____cpython.yaml
- .ci_support/osx_arm64_python3.9.____cpython.yaml
- recipe/meta.yaml
> release boa 0.3.3

- recipe/meta.yaml
> release 0.3.4

- recipe/meta.yaml
> release 0.3.5

- .ci_support/linux_aarch64_python3.6.____cpython.yaml
- .ci_support/linux_aarch64_python3.7.____cpython.yaml
- .ci_support/linux_aarch64_python3.8.____cpython.yaml
- .ci_support/linux_aarch64_python3.9.____cpython.yaml
- .ci_support/linux_ppc64le_python3.6.____cpython.yaml
- .ci_support/linux_ppc64le_python3.7.____cpython.yaml
- .ci_support/linux_ppc64le_python3.8.____cpython.yaml
- .ci_support/linux_ppc64le_python3.9.____cpython.yaml
- .drone.yml
- .travis.yml
- README.md
- conda-forge.yml
- recipe/meta.yaml
> Build aarch/ppc packages

- recipe/meta.yaml
> release 0.4.1

- recipe/meta.yaml
> release boa 0.5.0

- recipe/meta.yaml
> release boa 0.6.1

- recipe/meta.yaml
> release 0.6.2

- recipe/meta.yaml
> release boa 0.8.0

- recipe/meta.yaml
> release 0.9.0

- recipe/meta.yaml
> update conda-build constraint

- recipe/meta.yaml
> Update mamba condition

- .ci_support/linux_64_.yaml
- recipe/meta.yaml
> Bump `mamba` pin

- .scripts/build_steps.sh
- README.md
- recipe/meta.yaml
> Allow mamba 1.4

- recipe/meta.yaml
> release 0.15.1

- recipe/meta.yaml
> loosen ruamel.yaml lower bound

- .ci_support/linux_64_.yaml
- recipe/meta.yaml
Checklist
ref:
- https://github.com/conda-forge/boa-feedstock/issues/81#issuecomment-2028491556
Add missing conda dependency
Constrained to >=23.3 to avoid type mismatch for
boltons.setutils.IndexedSet and conda._vendor.boltons.setutils.IndexedSet
> Add conda dep
